//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net4.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public int id { get; set; }
        public string employee_name { get; set; }
        public Nullable<System.DateTime> date_of_birth { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public byte[] image_nv { get; set; }
        public string user_name { get; set; }
    
        public virtual user user { get; set; }
    }
}
