//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net4.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class game
    {
        public int id { get; set; }
        public int game_category_id { get; set; }
        public string game_name { get; set; }
        public int played_times { get; set; }
        public string path { get; set; }
        public byte[] image_url { get; set; }
    
        public virtual game_category game_category { get; set; }
    }
}
