//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net4.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class payment_detail
    {
        public int id { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<int> payment_id { get; set; }
        public Nullable<int> product_quantity { get; set; }
        public Nullable<int> total { get; set; }
    
        public virtual product product { get; set; }
    }
}
